### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by egli** [sbsdev/mdr2#72]
Error handling is not done so well in this project. Sometimes there are pipelines, threading macros really, that move a production through a series of steps. Some of these steps can fail due to issues in the file system: iso file not found, smil files not around, permissions not correct, etc.

It appears that sometimes exceptions are dropped and the work in the pipeline is continued because there is no clean way to handle errors in pipelines. This could probably be solved by using the error monad from [Failjure](https://github.com/adambard/failjure).

Other times the exceptions are not handled and cause (due to poor configuration of the message queue) a re-delivery of a message and cause the error to happen again only probably worse.

Generally what is a good strategy to handle errors? Should I 
- log and ignore the error
- crash and burn
- something in between

The real question here is probably how should I handle these errors. Due to the reliance no the file system, where users have access to, such exceptions are bound to happen and need to be handled. If an error happens the workflow state should not advance.

**Comment by egli** [comment]
Monitoring is of course closely related to this #71

**Comment by plexus** [comment]
Since you mention threading macros I'm guessing you have your operations fairly hard coded

``` clj
(-> start
    do-this
    do-that
    ,,,,)
```

that means there's some kind of thing getting passed from one step to the next. I would start by making sure that this is uniform, typically this is called a context map, which gets passed from step to step, and each step can inspect it and change it before passing it on.

Then you'll have to start adding exception handlers and if/then checks. If certain things prevent the process from continuing, then you should probably log that somewhere very clearly, and indicate in that context map that something went wrong and the rest of the steps can be skipped.

``` clj
(defn my-step [ctx]
  (if (:error ctx)
    ctx
    (try
      ,,, do work ,,,
     (assoc ctx :resource-for-the-next-step my-resource)
     (catch Exception e
       (log/error :my-step/failed {:parameter p} :exception e)
       (assoc ctx :error e :error-step "my-step")))))
```

This way you can also have a last step that takes some action if any step went wrong

``` clj
(defn report-errors [{:keys [error error-step project-id timestamp] :as ctx}]
  (when error
    (send-email-to-christian
     (str "Project " project-id " failed at " timestamp " during " error-step ".\n"
          "Exception: " error "\n"
          "Stack:" (.getStackTrace error))))
  ctx)
```

Now your pipeline becomes:

``` clj
(-> {:project-id 123
     :timestamp (Date.)
     :input (io/file "...")}
    my-step
    my-other-step
    report-errors)
```

Many variations on this but this is I think a good basic pattern to start from.

**Comment by egli** [comment]
This has a long history in the new code base. I went from plain exceptions to otto/nom, then to failjure and finally back to plain exceptions because you need exceptions to trigger rollback in database transactions.

All in all while it is still not the perfect solution, I think it is now handled more consistently with plain exceptions. Good enough for now
